# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: onedrive_client/entities/common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from onedrive_client.entities import onedrive_pb2 as onedrive__client_dot_entities_dot_onedrive__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='onedrive_client/entities/common.proto',
  package='onedrive_client.entities.common',
  syntax='proto3',
  serialized_pb=_b('\n%onedrive_client/entities/common.proto\x12\x1fonedrive_client.entities.common\x1a\'onedrive_client/entities/onedrive.proto\"3\n\x11LocalItemMetadata\x12\x0c\n\x04size\x18\x01 \x01(\x04\x12\x10\n\x08modified\x18\x02 \x01(\x04\"_\n\tLocalItem\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x44\n\x08metadata\x18\x02 \x01(\x0b\x32\x32.onedrive_client.entities.common.LocalItemMetadata\"Z\n\x0e\x44irtyLocalItem\x12\x0e\n\x06our_id\x18\x01 \x01(\x0c\x12\x38\n\x04item\x18\x02 \x01(\x0b\x32*.onedrive_client.entities.common.LocalItem\"X\n\x0f\x44irtyRemoteItem\x12\x0e\n\x06our_id\x18\x01 \x01(\x0c\x12\x35\n\x04item\x18\x02 \x01(\x0b\x32\'.onedrive_client.entities.onedrive.Itemb\x06proto3')
  ,
  dependencies=[onedrive__client_dot_entities_dot_onedrive__pb2.DESCRIPTOR,])




_LOCALITEMMETADATA = _descriptor.Descriptor(
  name='LocalItemMetadata',
  full_name='onedrive_client.entities.common.LocalItemMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='onedrive_client.entities.common.LocalItemMetadata.size', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modified', full_name='onedrive_client.entities.common.LocalItemMetadata.modified', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=166,
)


_LOCALITEM = _descriptor.Descriptor(
  name='LocalItem',
  full_name='onedrive_client.entities.common.LocalItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='onedrive_client.entities.common.LocalItem.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='onedrive_client.entities.common.LocalItem.metadata', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=263,
)


_DIRTYLOCALITEM = _descriptor.Descriptor(
  name='DirtyLocalItem',
  full_name='onedrive_client.entities.common.DirtyLocalItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='our_id', full_name='onedrive_client.entities.common.DirtyLocalItem.our_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item', full_name='onedrive_client.entities.common.DirtyLocalItem.item', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=355,
)


_DIRTYREMOTEITEM = _descriptor.Descriptor(
  name='DirtyRemoteItem',
  full_name='onedrive_client.entities.common.DirtyRemoteItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='our_id', full_name='onedrive_client.entities.common.DirtyRemoteItem.our_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item', full_name='onedrive_client.entities.common.DirtyRemoteItem.item', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=357,
  serialized_end=445,
)

_LOCALITEM.fields_by_name['metadata'].message_type = _LOCALITEMMETADATA
_DIRTYLOCALITEM.fields_by_name['item'].message_type = _LOCALITEM
_DIRTYREMOTEITEM.fields_by_name['item'].message_type = onedrive__client_dot_entities_dot_onedrive__pb2._ITEM
DESCRIPTOR.message_types_by_name['LocalItemMetadata'] = _LOCALITEMMETADATA
DESCRIPTOR.message_types_by_name['LocalItem'] = _LOCALITEM
DESCRIPTOR.message_types_by_name['DirtyLocalItem'] = _DIRTYLOCALITEM
DESCRIPTOR.message_types_by_name['DirtyRemoteItem'] = _DIRTYREMOTEITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LocalItemMetadata = _reflection.GeneratedProtocolMessageType('LocalItemMetadata', (_message.Message,), dict(
  DESCRIPTOR = _LOCALITEMMETADATA,
  __module__ = 'onedrive_client.entities.common_pb2'
  # @@protoc_insertion_point(class_scope:onedrive_client.entities.common.LocalItemMetadata)
  ))
_sym_db.RegisterMessage(LocalItemMetadata)

LocalItem = _reflection.GeneratedProtocolMessageType('LocalItem', (_message.Message,), dict(
  DESCRIPTOR = _LOCALITEM,
  __module__ = 'onedrive_client.entities.common_pb2'
  # @@protoc_insertion_point(class_scope:onedrive_client.entities.common.LocalItem)
  ))
_sym_db.RegisterMessage(LocalItem)

DirtyLocalItem = _reflection.GeneratedProtocolMessageType('DirtyLocalItem', (_message.Message,), dict(
  DESCRIPTOR = _DIRTYLOCALITEM,
  __module__ = 'onedrive_client.entities.common_pb2'
  # @@protoc_insertion_point(class_scope:onedrive_client.entities.common.DirtyLocalItem)
  ))
_sym_db.RegisterMessage(DirtyLocalItem)

DirtyRemoteItem = _reflection.GeneratedProtocolMessageType('DirtyRemoteItem', (_message.Message,), dict(
  DESCRIPTOR = _DIRTYREMOTEITEM,
  __module__ = 'onedrive_client.entities.common_pb2'
  # @@protoc_insertion_point(class_scope:onedrive_client.entities.common.DirtyRemoteItem)
  ))
_sym_db.RegisterMessage(DirtyRemoteItem)


# @@protoc_insertion_point(module_scope)
