# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: onedrive_client/RPC_protoc_plugins/plugin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from onedrive_client.RPC import RPC_pb2 as onedrive__client_dot_RPC_dot_RPC__pb2
from google.protobuf.compiler import plugin_pb2 as google_dot_protobuf_dot_compiler_dot_plugin__pb2

from google.protobuf.compiler.plugin_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='onedrive_client/RPC_protoc_plugins/plugin.proto',
  package='onedrive_client.RPC.plugin',
  syntax='proto3',
  serialized_pb=_b('\n/onedrive_client/RPC_protoc_plugins/plugin.proto\x12\x1aonedrive_client.RPC.plugin\x1a\x1donedrive_client/RPC/RPC.proto\x1a%google/protobuf/compiler/plugin.protoP\x01\x62\x06proto3')
  ,
  dependencies=[onedrive__client_dot_RPC_dot_RPC__pb2.DESCRIPTOR,google_dot_protobuf_dot_compiler_dot_plugin__pb2.DESCRIPTOR,],
  public_dependencies=[google_dot_protobuf_dot_compiler_dot_plugin__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
