# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tests/service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from onedrive_client.RPC import RPC_pb2 as onedrive__client_dot_RPC_dot_RPC__pb2
from tests import entities_pb2 as tests_dot_entities__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tests/service.proto',
  package='tests.service',
  syntax='proto3',
  serialized_pb=_b('\n\x13tests/service.proto\x12\rtests.service\x1a\x1donedrive_client/RPC/RPC.proto\x1a\x14tests/entities.proto\x1a\x1bgoogle/protobuf/empty.proto2a\n\x0bSpamService\x12L\n\x03\x42\x61r\x12\x13.tests.entities.Foo\x1a\x16.google.protobuf.Empty\"\x18\x80\xb5\x18\x01\x8a\xb5\x18\x10REQUEST_RESPONSE\x1a\x04\x80\xb5\x18\x01\x42\x03\x90\x01\x01\x62\x06proto3')
  ,
  dependencies=[onedrive__client_dot_RPC_dot_RPC__pb2.DESCRIPTOR,tests_dot_entities__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\220\001\001'))

_SPAMSERVICE = _descriptor.ServiceDescriptor(
  name='SpamService',
  full_name='tests.service.SpamService',
  file=DESCRIPTOR,
  index=0,
  options=_descriptor._ParseOptions(descriptor_pb2.ServiceOptions(), _b('\200\265\030\001')),
  serialized_start=120,
  serialized_end=217,
  methods=[
  _descriptor.MethodDescriptor(
    name='Bar',
    full_name='tests.service.SpamService.Bar',
    index=0,
    containing_service=None,
    input_type=tests_dot_entities__pb2._FOO,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\200\265\030\001\212\265\030\020REQUEST_RESPONSE')),
  ),
])
_sym_db.RegisterServiceDescriptor(_SPAMSERVICE)

DESCRIPTOR.services_by_name['SpamService'] = _SPAMSERVICE

SpamService = service_reflection.GeneratedServiceType('SpamService', (_service.Service,), dict(
  DESCRIPTOR = _SPAMSERVICE,
  __module__ = 'tests.service_pb2'
  ))

SpamService_Stub = service_reflection.GeneratedServiceStubType('SpamService_Stub', (SpamService,), dict(
  DESCRIPTOR = _SPAMSERVICE,
  __module__ = 'tests.service_pb2'
  ))


# @@protoc_insertion_point(module_scope)
